:source-highlighter: highlightjs
:icons: font
:revealjs_theme: solarized

= Codons un jeu du pendu

[,txt]
----
                                |        #####
                                |        #   |
                                |        #
                                |        #
    V_LC_MP 12 _CT_BR_ 2023     |    #########
----

== Qui me parle ?

Anthony REY:: Développeur CSS chez Ippon
Nolwenn DOUCET:: Développeur adepte des machins DD chez Ideme

== Objectifs

* Apprendre
* Partager
* Peut-être finir le kata

== Kata et TDD

=== Un kata

C’est un exercice de code (en création ou en refactoring) facilement appréhendable et qui peut être recommencé à l’envie

=== TDD

C’est une technique de design de code qui s’articule autour d’une boucle

. Écrire un test
. Le faire échouer (faut que ça compile)
. Écrire l’implémentation la plus directe
. Améliorer l’existant (important toujours refactorer quand on est en vert)
. Reprendre en *1*

=== Déroulé de l’atelier

10h15 – 10h30:: Présentation et mise en place des binômes
10h30 – 11h00:: Première itération sans guide
11h00 – 11h10:: Rétrospective intermédiaire

=== Déroulé de l’atelier

11h10 - 11h15:: Nouveaux binôme
11h15 – 12h00:: Seconde itération avec des contraintes
12h00 – 12h15:: Rétrospective

== Première itération
=== Jusqu’à 11h00
Règles métier:: 
* `_` est le caractère masquant
* Insensible à la casse
* Que des lettres
* Afficher le nombre d’erreurs

== Rétrospective intermédiaire

== Seconde itération

=== Jusqu’à 12h00
Contraintes:: 
* Ne jamais exposer le secret
* Tout petit pas, commit toutes les deux minutes maximum
* Immutabilité
Règles métier::
* Un jeu terminé ne permet plus de jouer
* Proposer une lettre déjà trouvée est une erreur

== Rétrospective globale
